### ISSUE TITLE
Initial EMISO Engine

### ISSUE THREAD

**Issue by jmi-reds** [smartobjectoriented/emiso#4]
This issue follows activities on the creation on an initial version of the EMISO Engine. 

The target is to be able to create an environment from Portainer server (connect with the Smart Object).

**Task list**:

*Rootfs*
   * [X] Add "curl" and "python-docker": it will use to send commands to EMISO engine for debug/test
   * [X] A support of "systemd": simplify the management of the services. It can be used to start/stop `dockerd` for test purpose.  

*Webserver*
* [X] Basic Restfull web server which respond to GET and POST commands 
* [X] Basic commands used by Portnair to connect with environments (cmd list below) / Return default valid message hardcoded massages

**Milestone** - At this point Portainer Server can connect with a dummy environment 

*Daemon*
* [ ] Answer to the commands sent from the *Webserver* (dummy answers)
* [ ] Implementation of the real answer to the commands 

**Milestone** - In Portainer Server get the real information from the environment 

Here is the list of the commands sent by _Portainer_ during an environment connection:
*  [X]  _ping
* [X] info
* [X] containers/json
* [x] images/json
* [X] volumes - returns empty value (volumes not handled by emiso)
* [X] networks - returns empty value (networks not handled by emiso)
* [X] version

**Comment by jmi-reds** [comment]
Here is an example on how to use `curl` and `python` to interact with Docker daemon and EMISO webserver. 

## Get the list of containers 

*HTTP*
```
curl --unix-socket /var/run/docker.sock http://localhost/containers/json
```
*Python*
```
import docker
client = docker.from_env()
for container in client.containers.list():
  print(container.id)
```

**Comment by jmi-reds** [comment]
An initial version of a webserver has been integrated. It works in HTTPS/TLS.
Currently it only prints the GET / POST received. 

Command example: `curl -X GET -k "https://192.168.53.154:8080/images/json"`

The code also provides an version based on sockets. It is made for testing.

**Comment by jmi-reds** [comment]
Just a note about TLS configuration in _Portainer_: currently, it is not possible to enable TLS with _Skip Certification Verification_ option enabled.
* ref: https://github.com/portainer/portainer/issues/8011
